[package]
name = "cave"
version = "0.1.0"
edition = "2024"

[dependencies]
godot = { version = "0.3.5", features = ["experimental-wasm", "lazy-function-tables"] }
snafu = "0.8.9"

[lib]
crate-type = ["cdylib"]
